export const IMAGES = {

    /*....gif......*/
    rightGif: require('../assets/gif/rightGif.gif'),
    /*...images......*/
    firstScreen: require('../assets/images/firstScreen.png'),
    secondScreen: require('../assets/images/secondScreen.png'),
    loginScreenImg: require('../assets/images/loginScreenImg.png'),
    backgroundLogin: require('../assets/images/backgroundLogin.png'),
    LanguageBackground: require('../assets/images/LanguageBackground.png'),
    OtpBackground: require('../assets/images/OtpBackground.png'),
    language: require('../assets/images/language.png'),
    Arabic: require('../assets/images/Arabic.png'),
    French: require('../assets/images/French.png'),
    backGround: require('../assets/images/backGround.png'),
    En: require('../assets/images/En.jpg'),
   
     /*...icon......*/
     blueRight: require('../assets/icon/blueRight.png'),
     arrow: require('../assets/icon/arrow.png'),
     focusedprofile: require('../assets/icon/focusedprofile.png'),
     unfocusedlock: require('../assets/icon/unfocusedlock.png'),
     backArrow: require('../assets/icon/backArrow.png'),
     focusedLock: require('../assets/icon/focusedLock.png'),
     unfocusedprofile: require('../assets/icon/unfocusedprofile.png'),
     UnfocusedEmail: require('../assets/icon/UnfocusedEmail.png'),
     focusedEmail: require('../assets/icon/focusedEmail.png'),
     focusedPhone: require('../assets/icon/focusedPhone.png'),
     UnfocusedPhone: require('../assets/icon/UnfocusedPhone.png'),
     other: require('../assets/icon/other.png'),
     female: require('../assets/icon/female.png'),
     male: require('../assets/icon/male.png'),
     focusedcalendar: require('../assets/icon/focusedcalendar.png'),
     unfocusedcalendar: require('../assets/icon/unfocusedcalendar.png'),
     greyArrow: require('../assets/icon/greyArrow.png'),
     blueArrow: require('../assets/icon/blueArrow.png'),
     message: require('../assets/icon/blueArrow.png'),
     whitebackArrow: require('../assets/icon/whitebackArrow.png'),
     filterIcon: require('../assets/icon/filter.png'),
     searchIcon: require('../assets/icon/search.png'),
     doctorIcon: require('../assets/icon/doctorIcon.png'),
     specializationIcon: require('../assets/icon/specializationIcon.png'),
     clinicIcon: require('../assets/icon/clinicIcon.png'),
     StarIcon: require('../assets/icon/Star.png'),
}  