export const IMAGES = {
  /*....gif......*/
  rightGif: require('../assets/gif/rightGif.gif'),
  /*...images......*/
  firstScreen: require('../assets/images/firstScreen.png'),
  secondScreen: require('../assets/images/secondScreen.png'),
  loginScreenImg: require('../assets/images/loginScreenImg.png'),
  backgroundLogin: require('../assets/images/backgroundLogin.png'),
  LanguageBackground: require('../assets/images/LanguageBackground.png'),
  OtpBackground: require('../assets/images/OtpBackground.png'),
  language: require('../assets/images/language.png'),
  Arabic: require('../assets/images/Arabic.png'),
  French: require('../assets/images/French.png'),
  En: require('../assets/images/En.jpg'),
  profile: require('../assets/images/Ellipse718.png'),
  flag: require('../assets/images/Rectangle10.png'),
  kidney: require('../assets/images/1f1ede28-eb24-4ddd-929e-ee83ae9aecc7sd1.png'),
  ear: require('../assets/images/earsa1.png'),
  tablet: require('../assets/images/Tablet.H03.2k1.png'),
  lungs: require('../assets/images/24740e0c-b1b1-4b90-9271-3e7943dc05f41.png'),
  brain: require('../assets/images/Maskgroup.png'),
  heart: require('../assets/images/vuefxiwkxzxzxz1.png'),
  DoctorProfile: require('../assets/images/DoctorPhoto.png'),
  doctorImg: require('../assets/images/Rectangle5652.png'),
  bg: require('../assets/images/Bg.png'),

  /*...icon......*/
  blueRight: require('../assets/icon/blueRight.png'),
  arrow: require('../assets/icon/arrow.png'),
  focusedprofile: require('../assets/icon/focusedprofile.png'),
  unfocusedlock: require('../assets/icon/unfocusedlock.png'),
  backArrow: require('../assets/icon/backArrow.png'),
  focusedLock: require('../assets/icon/focusedLock.png'),
  unfocusedprofile: require('../assets/icon/unfocusedprofile.png'),
  UnfocusedEmail: require('../assets/icon/UnfocusedEmail.png'),
  focusedEmail: require('../assets/icon/focusedEmail.png'),
  focusedPhone: require('../assets/icon/focusedPhone.png'),
  UnfocusedPhone: require('../assets/icon/UnfocusedPhone.png'),
  other: require('../assets/icon/other.png'),
  female: require('../assets/icon/female.png'),
  male: require('../assets/icon/male.png'),
  focusedcalendar: require('../assets/icon/focusedcalendar.png'),
  unfocusedcalendar: require('../assets/icon/unfocusedcalendar.png'),
  greyArrow: require('../assets/icon/greyArrow.png'),
  blueArrow: require('../assets/icon/blueArrow.png'),
  message: require('../assets/icon/image51.png'),
  wallet: require('../assets/icon/wallet1.png'),
  bell: require('../assets/icon/bell-notification-social-media1.png'),
  dropdown: require('../assets/icon/gridicons_dropdown.png'),
  calendar: require('../assets/icon/calendar-day1.png'),
  calendarTick: require('../assets/icon/calendar-tick.png'),
  arrowRight: require('../assets/icon/arrow-right.png'),
  clock: require('../assets/icon/clock.png'),
  send: require('../assets/icon/send-2.png'),
  messageTxt: require('../assets/icon/message-text.png'),
  vector: require('../assets/icon/Vector.png'),
};
