import {StyleSheet} from 'react-native';
import {
  horizontalScale,
  verticalScale,
  horizontalMarginScale,
  verticalMarginScale,
  fontScale,
  radiusScale,
} from '../../utils/DimensionConstant';
import {Fonts} from '../../utils/Constants';
const SPACING = 15;
const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: 'white',
    // padding: 15,
    paddingHorizontal: horizontalScale(20),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginVertical: verticalMarginScale(15),
    // height: verticalScale(130),
    // borderWidth: 2,
    // borderColor: 'black',
  },
  leftView: {
    width: horizontalScale(75),
    height: verticalScale(75),
  },
  leftImg: {
    margin: 'auto',
    height: verticalScale(70),
    width: horizontalScale(70),
    borderRadius: radiusScale(50),
    // borderColor: 'green',
    // borderWidth: 1,
  },
  rightView: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: horizontalScale(145),
    marginTop: verticalMarginScale(25),
    // backgroundColor:'red',
  },
  rightImg: {
    height: verticalScale(25),
    width: horizontalScale(25),
  },
  dropdown: {
    flexDirection: 'row',
    alignItems: 'center',

    // marginTop: verticalMarginScale(10),
  },
  dropdownImg: {
    height: verticalScale(40),
    width: horizontalScale(40),
  },
  heading: {
    fontFamily: Fonts.Bold,
    fontSize: fontScale(34),
  },
  calendar: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginTop: verticalMarginScale(10),
  },
  calImg: {
    height: verticalScale(25),
    width: horizontalScale(25),
    marginRight: horizontalMarginScale(10),
  },
  calText: {
    fontFamily: Fonts.Light,
    fontSize: fontScale(16),
  },
  subHeading: {
    marginTop: verticalMarginScale(30),
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  eventHead: {
    color: '#323232',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(18),
  },
  eventText: {
    color: '#09F',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(14),
  },
  eventContainer: {
    height: verticalScale(212),
    // width: CARD_WIDTH,
    // width: horizontalScale(315),
    backgroundColor: '#09F',
    borderRadius: 20,
    marginTop: verticalMarginScale(20),
    paddingTop: 15,
    paddingBottom: 15,
    paddingLeft: 15,
    // margin: horizontalMarginScale(10),
    marginRight: SPACING,
    // marginLeft
    justifyContent: 'space-between',
  },
  top: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalMarginScale(10),
    marginRight: 15,
  },
  topText: {
    color: '#FFF',
    fontSize: fontScale(14),
    fontFamily: Fonts.SemiBold,
  },
  topArrow: {
    height: verticalScale(16),
    width: horizontalScale(16),
    alignItems: 'center',
    justifyContent: 'center',
  },
  mid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: verticalMarginScale(25),
    marginRight: 15,
  },
  midLeft: {
    width: horizontalScale(150),
  },
  midSub: {
    flexDirection: 'row',
    // justifyContent: 'space-around',
    marginBottom: verticalMarginScale(5),
    // backgroundColor: 'red',
  },
  midImg: {
    height: verticalScale(18),
    width: horizontalScale(18),
    marginRight: horizontalMarginScale(5),
  },
  midText: {
    color: '#FFF',
    fontSize: fontScale(14),
    fontFamily: Fonts.Medium,
  },
  midRight: {
    backgroundColor: '#FFF',
    borderRadius: 100,
    width: horizontalScale(50),
    height: verticalScale(50),
    alignItems: 'center',
    justifyContent: 'center',
  },
  midRightImg: {
    // display:'flex',
    width: horizontalScale(24),
    height: verticalScale(24),
    // alignItems: 'center',
    // justifyContent: 'center',
  },
  bottom: {
    flexDirection: 'row',
    backgroundColor: '#FFF',
    borderRadius: 15,
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    marginRight: 15,
    // marginBottom:verticalMarginScale(0),
  },
  docInfo: {
    height: verticalScale(40),
    width: horizontalScale(166),
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  docImg: {
    height: verticalScale(40),
    width: horizontalScale(40),
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: horizontalMarginScale(5),
  },
  docName: {
    color: '#070C18',
    fontFamily: Fonts.Bold,
    fontSize: fontScale(14),
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  docSpec: {
    color: '#727A83',
    fontFamily: Fonts.Regular,
    fontSize: fontScale(12),
    lineHeight: 20,
    letterSpacing: 0.2,
  },
  docMsg: {
    height: verticalScale(20),
    width: horizontalScale(20),
    justifyContent: 'center',
    alignItems: 'center',
  },
  speContainer: {
    marginTop: verticalMarginScale(20),
    // padding: 10,
  },
  subContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    marginBottom: verticalMarginScale(20),
    // backgroundColor: 'black',
    // paddingLeft: 10,
    // paddingRight:10,
  },
  container: {
    height: verticalScale(177),
    width: horizontalScale(150),
    borderRadius: radiusScale(24),
    borderColor: '#E4DDFF',
    borderWidth: 1,
    backgroundColor: '#FFFFFF4F',
    // borderColor: 'green',
    // borderWidth: 1,
  },
  largeImgContainer: {
    height: verticalScale(175),
    width: horizontalScale(330),
    borderRadius: radiusScale(24),
    borderColor: '#E4DDFF',

    borderWidth: 1,
    backgroundColor: '#FFFFFF4F',
    justifyContent: 'center',
    alignItems: 'center',
  },
  largeImg: {
    // borderWidth: 2,
    // borderColor: 'black',
    height: verticalScale(175),
    width: horizontalScale(340),
    borderRadius: radiusScale(24),
  },
  largeImgText: {
    height: verticalScale(40),
    width: horizontalScale(300),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: 'white',
    borderWidth: 1,
    backgroundColor: '#FFFFFF99',
    borderRadius: radiusScale(10),
    margin: 'auto',
    marginTop: verticalMarginScale(105),
  },
  specImg: {
    height: verticalScale(175),
    width: horizontalScale(148),
    borderRadius: radiusScale(24),
    borderColor: '#E4DDFF',
  },
  specText: {
    height: verticalScale(40),
    width: horizontalScale(148),
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#FFFFFF98',
    borderWidth: 1,
    backgroundColor: '#FFFFFF99',
    borderRadius: radiusScale(10),
    marginTop: verticalMarginScale(105),
  },
});
export default styles;
